language: java

# installing python3

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5 # for mjtest, no less than 3.5...
before_install:
  - echo $PATH
  - sudo rm -f /usr/bin/python3 # whatever
  - sudo ln -s /usr/bin/python3.5 /usr/bin/python3

# caching

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# actual build stuff

jdk:
  - oraclejdk8
env:
  - TERM=dumb
script:
  - ./gradlew check --stacktrace
